- Amministrazione:
    - Tailscale:
        - icon: tailscale.png
          href: https://login.tailscale.com/admin/machines
    - Repository PiServer:
        - icon: github.png
          href: https://github.com/GianniGiuffo/PiServer
